# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from mongoengine import *


class Users(Document):
    _id = ObjectIdField()
    id = IntField()
    name = StringField()
    gender = IntField()
    vote_from_count = IntField()
    pins_count = IntField()
    favorite_count = IntField()
    answer_count = IntField()
    follower_count = IntField()
    voteup_count = IntField()
    commercial_question_count = IntField()
    following_columns_count = IntField()
    following_topic_count = IntField()
    participated_live_count = IntField()
    hosted_live_count = IntField()
    thank_to_count = IntField()
    mutual_followees_count = IntField()
    following_favlists_count = IntField()
    thank_from_count = IntField()
    marked_answers_count = IntField()
    question_count = IntField()
    articles_count = IntField()
    vote_to_count = IntField()
    type = StringField()
    description =StringField()
    headline = StringField()
    avatar_url = StringField()
    url_token = StringField()
    url = StringField()
    cover_url = StringField()
    badge = StringField()
    locations = ListField()
    educations = ListField()
    employments = ListField()
    thanked_count = IntField()
    favorited_count = IntField()
    following_count = IntField()
    following_question_count = IntField()

class Answers(Document):
    _id = ObjectIdField()
    id = IntField()
    question = IntField()
    url = StringField()
    thumbnail = StringField()
    content = StringField()
    author = StringField()
    voteup_count = IntField()
    comment_count = IntField()

class Questions(Document):
    _id = ObjectIdField()
    id = IntField()
    title = StringField()
    type = StringField()
    url = StringField()
    created = IntField()
